### ISSUE TITLE
About one image

### ISSUE THREAD

**Issue by Wangld5** [GDam90/Fashion_IQ_missing_images#1]
Hi
The image http://ecx.images-amazon.com/images/I/51WUqJu-tKL._SY445_.jpg is not included in the image data. Can you find it ?

**Comment by GDam90** [comment]
Hi,
Actually i can't find this specific image (asin B000NKXU22), but in the zip file I suggested you there are all the asins contained in all the splits (dress/shirt/toptee and train, val, test). Maybe this specific image is not used in the dataset.

**Comment by Wangld5** [comment]
Thank you, It is not included in the three splits.
